### ISSUE TITLE
question about the version of the dependencies

### ISSUE THREAD

**Issue by QDZ123** [iqiukp/SVDD#10]
Hi, I am working on training this svdd model on my own data.But, I encountered an error "TypeError: np.matrix is not supported" when I tried to run the code. It seems that you have answered this question before and think it might be a version issue with the dependencies. So I would like to ask, what versions of the dependencies do you have?
Thank you!!

**Comment by iqiukp** [comment]
Hi. We have fixed the bug. The project can works on the latest version of cvxopt ( v1.2.6).
