### ISSUE TITLE
I think there is a problem with R expression in linear kernel hard-marginal SVDD

### ISSUE THREAD

**Issue by Longchao1047027852** [iqiukp/SVDD#11]
self.radius = np.sqrt(np.mean(np.diag(K)) + self.offset+np.mean(tmp_[self.boundary_indices, 0])),
![image](https://github.com/iqiukp/SVDD-Python/assets/72878236/c9f6da1c-6c02-4836-a703-78566a9fb9b2),this's the result of the corresponding code.
 R = 1.53,  but the  distance of support_vectors is  3.53

**Comment by luoh226** [comment]
I have the same question

**Comment by luoh226** [comment]
I solve this bug through replacing https://github.com/iqiukp/SVDD-Python/blob/b96604a5aeb33533fef1f9c00ca75d036126cd8f/src/BaseSVDD.py#L281 to `self.radius = np.sqrt(np.mean(np.diag(K)[self.boundary_indices]) + self.offset + np.mean(tmp_[self.boundary_indices, 0]))`.
But I not shure is right implement in Support Vector Data Description.
![image](https://github.com/iqiukp/SVDD-Python/assets/63135179/398b23b9-9ea6-4435-b694-417774f54295)
![image](https://github.com/iqiukp/SVDD-Python/assets/63135179/97e5401d-f007-44da-9999-c7442c2fef93)
@Longchao1047027852 @iqiukp

**Comment by iqiukp** [comment]
Hi. Thanks for supporting the project. This has been fixed in the latest version, thanks @Longchao1047027852 @D3mianGianoz
