### ISSUE TITLE
domain error

### ISSUE THREAD

**Issue by diadai** [iqiukp/SVDD#2]
“
File "D:\program\Code\Python\DW-SVDD\src\parameters_optimization_svdd.py", line 84, in train
    alf, obj, iteration = self.quadprog(K, train_label)
  File "D:\program\Code\Python\DW-SVDD\src\parameters_optimization_svdd.py", line 311, in quadprog
    sol = solvers.qp(P, q, G, h, A, b)
  File "D:\program\python\lib\site-packages\cvxopt\coneprog.py", line 4485, in qp
    return coneqp(P, q, G, h, None, A,  b, initvals, kktsolver = kktsolver, options = options)
  File "D:\program\python\lib\site-packages\cvxopt\coneprog.py", line 2519, in coneqp
    misc.update_scaling(W, lmbda, ds, dz)
  File "D:\program\python\lib\site-packages\cvxopt\misc.py", line 450, in update_scaling
    s[:m] = base.sqrt( s[:m] )
ValueError: domain error
”
在一些数据集上做十倍交叉验证，不同的训练集会出现以上的错误。SVDD部分，没有进行任何更改，看了很多资料，仍然未找到方法，特来请教博主，不胜感激！

**Comment by iqiukp** [comment]
> “
> File "D:\program\Code\Python\DW-SVDD\src\parameters_optimization_svdd.py", line 84, in train
> alf, obj, iteration = self.quadprog(K, train_label)
> File "D:\program\Code\Python\DW-SVDD\src\parameters_optimization_svdd.py", line 311, in quadprog
> sol = solvers.qp(P, q, G, h, A, b)
> File "D:\program\python\lib\site-packages\cvxopt\coneprog.py", line 4485, in qp
> return coneqp(P, q, G, h, None, A, b, initvals, kktsolver = kktsolver, options = options)
> File "D:\program\python\lib\site-packages\cvxopt\coneprog.py", line 2519, in coneqp
> misc.update_scaling(W, lmbda, ds, dz)
> File "D:\program\python\lib\site-packages\cvxopt\misc.py", line 450, in update_scaling
> s[:m] = base.sqrt( s[:m] )
> ValueError: domain error
> ”
> 在一些数据集上做十倍交叉验证，不同的训练集会出现以上的错误。SVDD部分，没有进行任何更改，看了很多资料，仍然未找到方法，特来请教博主，不胜感激！

你好。这个问题很可能出现在10折交叉验证过程中，数据集和标签的分割结果导致 K 和 train_label 的值异常。你设置一个断点分别输出 K 和 train_label 的值和数据类型。和原始 SVDD demo对比一下。平时很少用 Python，所以这里的SVDD只是实现了一个基本功能。

可以尝试把 K 折的值换小点，或者是手动拆分数据集和标签再试试。

**Comment by diadai** [comment]
> > “
> > File "D:\program\Code\Python\DW-SVDD\src\parameters_optimization_svdd.py", line 84, in train
> > alf, obj, iteration = self.quadprog(K, train_label)
> > File "D:\program\Code\Python\DW-SVDD\src\parameters_optimization_svdd.py", line 311, in quadprog
> > sol = solvers.qp(P, q, G, h, A, b)
> > File "D:\program\python\lib\site-packages\cvxopt\coneprog.py", line 4485, in qp
> > return coneqp(P, q, G, h, None, A, b, initvals, kktsolver = kktsolver, options = options)
> > File "D:\program\python\lib\site-packages\cvxopt\coneprog.py", line 2519, in coneqp
> > misc.update_scaling(W, lmbda, ds, dz)
> > File "D:\program\python\lib\site-packages\cvxopt\misc.py", line 450, in update_scaling
> > s[:m] = base.sqrt( s[:m] )
> > ValueError: domain error
> > ”
> > 在一些数据集上做十倍交叉验证，不同的训练集会出现以上的错误。SVDD部分，没有进行任何更改，看了很多资料，仍然未找到方法，特来请教博主，不胜感激！
> 
> 你好。这个问题很可能出现在10折交叉验证过程中，数据集和标签的分割结果导致 K 和 train_label 的值异常。你设置一个断点分别输出 K 和 train_label 的值和数据类型。和原始 SVDD demo对比一下。平时很少用 Python，所以这里的SVDD只是实现了一个基本功能。
> 
> 可以尝试把 K 折的值换小点，或者是手动拆分数据集和标签再试试。


非常感谢您的回复，我马上试一下🤭，向您学习！
