### ISSUE TITLE
gamma 'auto' or 'scale' is not handled and results in error

### ISSUE THREAD

**Issue by pirofti** [iqiukp/SVDD#6]
Hi,

The [documentation](https://github.com/iqiukp/SVDD-Python/blob/master/src/BaseSVDD.py#L33) states that gamma permits 'auto' or 'scale' , but the parameter handling passes it off as it is and an Exception occurs when `K *= gamma` is executed in sklearn as called from `pairwise_kernels()` [here](https://github.com/iqiukp/SVDD-Python/blob/master/src/BaseSVDD.py#L165).

My guess is that this is due to a copy paste leftover from OC-SVM or some similar estimator inside `sklearn`.

Thank you,
Paul

**Comment by iqiukp** [comment]
Hi, Paul

Thanks for your warm advice. I have fixed this bug in the newest [BaseSVDD.py](https://github.com/iqiukp/SVDD-Python/blob/master/src/BaseSVDD.py).

Best regards,
Kepeng Qiu
