### ISSUE TITLE
Support vectors incorrect

### ISSUE THREAD

**Issue by ludosGit** [iqiukp/SVDD#8]
Hi! I have a problem with the code: if I plot data in 2D from two normal distributions and fit the svdd with linear kernel, the support vectors in the plot_boundary are totally not aligned with the boundary (some are even inside). I see this happened also in your script svdd_example_kernel.py with the polynomial kernel.I tried to make my own plot but the issue remains.
Thank you! Ludovico

**Comment by iqiukp** [comment]
Hi. The accuracy of the boundaries depends on the number of grid points. This value can be modified by

    def plot_boundary(self, X, y=None, expand_ratio=0.2, n_grids=50, 
                      color_map='RdYlBu', n_level=6):
